version: '3.9'
services:

  db:

    image: postgres

    ports:
      - 5435:5432

    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: thePengStore

  web:

    build: .

    ports:
      - 8000:8000
      - 4173:4173

    volumes:
      - .:/app

    depends_on:
      - db
